//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs_Portal_Reporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> jobID { get; set; }
        public Nullable<System.DateTime> appliedAt { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}
