//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jobs_Portal_Reporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Applications = new HashSet<Application>();
            this.Interviews = new HashSet<Interview>();
        }
    
        public int ID { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string designation { get; set; }
        public string skills { get; set; }
        public string location { get; set; }
        public string department { get; set; }
        public string minEducation { get; set; }
        public Nullable<int> minExperience { get; set; }
        public Nullable<int> minAge { get; set; }
        public Nullable<int> maxAge { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> closingDate { get; set; }
        public Nullable<int> salary { get; set; }
        public string benefits { get; set; }
        public string document { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Applications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interviews { get; set; }
    }
}
